### ISSUE TITLE
Statick won't accept custom configuration for `clang-format`

### ISSUE THREAD

**Issue by jhdcs** [sscpac/statick#338]
While I was working on configuring Statick, I noticed that I can't set up a custom configuration for `clang-format`. If I deviate in any way from the format file included in Statick, I will get an error.

After looking around for a while, my colleague noticed the following function:

https://github.com/sscpac/statick/blob/e7ef6c1ff9f2b347307d24ca87fccbac97a25a76/statick_tool/plugins/tool/clang_format_tool_plugin.py#L131

We think that this function might be over-sensitive, and preventing any custom `clang-format` configuration files.

**Comment by tdenewiler** [comment]
How are you trying to use a custom configuration file for the `clang-format` tool? The only way I know how to do that when running Statick is to copy the desired `_clang-format` or `.clang-format` file into the users home directory. Statick will first look for `~/_clang-format`. If that file does not exist then it will use `~/.clang-format`.

The `clang-format` tool does not allow users to specify a path to a custom configuration file, which is why the code for that plugin jumps through more hoops than other tools. Those extra hoops also mean a higher chance we have a bug that needs to be fixed. 

I am using a custom `clang-format` configuration during CI for my node_example package. Here is where I copy that file into my home directory prior to running Statick.

https://github.com/tdenewiler/node_example/blob/6101a23fe93d442876c3feab8515eb00c283bf57/.github/workflows/test.yml#L121

**Comment by mlanting** [comment]
The only way we were able to get it to work was by copying the _clang-format file that comes with statick into the user's home directory. Other files were not accepted, even changing one of the values from true to false wasn't allowed. The "check_configuration" function appears to be taking the version in the users home directory and running a diff between it and the version in statick's rsc folder and throwing an exception if there are differences.

**Comment by tdenewiler** [comment]
When you run Statick are you passing in a `--user-paths` argument that is pointed to a directory containing your custom `_clang-format` file? Statick should be doing a diff between the `_statick_config` in the path pointed to by `--user-paths` and the one in the home directory. I say should based on a few projects where I see custom `clang-format` configuration files being used. However, I'll take a closer look at the code this morning.

**Comment by tdenewiler** [comment]
Your description of what is happening is correct. I can see why that is not so clear and obvious. The whole thing would be a lot easier if `clang-format` supported specifying a specific file. There have been attempts to add that in the past but I don't think they have landed yet.

https://reviews.llvm.org/D33560

I'll add a section to the README to make this more explicit.

**Comment by tdenewiler** [comment]
I updated the documentation in #337 in case you want to take a look.

**Comment by mlanting** [comment]
I assume you mean #339 ?

**Comment by tdenewiler** [comment]
I did mean #339, sorry about that.

**Comment by mlanting** [comment]
Thanks for your help Thomas, the documentation updates look good.
