### ISSUE TITLE
statick Docker images contain wrong version of statick

### ISSUE THREAD

**Issue by gregtkogut** [sscpac/statick#426]
Published Docker images appear to contain a version of statick one release older than the version tag used on the Docker image.

E.g. _ghcr.io/sscpac/statick:0.8.1_ contains statick==v0.8.0 and _ghcr.io/sscpac/statick:0.8.0_ contains statick==v0.7.2.

This should be fixed.

**Comment by gregtkogut** [comment]
I've figured out the root cause.  Manually triggering the build-and-publish workflow results in the correct version of statick being pulled into the image.  The published _ghcr.io/sscpac/statick:0.8.1_ is now correct.

The problem is a timing issue...this bulid-and-release gets triggered automatically when the release tag is generated, and that's before the the statick Python package is pushed to PyPI.  So it just gets the current latest version.

The Docker workflow could be changed to explicitly pin the statick version, but that would probably just result in an error.  

The immediate fix might be just to remove the workflow trigger and manually trigger it on a release.  

The slick thing to do would be to automatically trigger the PyPI publish (it doesn't appear to be automatic right now), and have that be a dependency on the Docker build.    But releases aren't so frequent that manually trigger is a huge deal.

I believe @denewiler  is the release-master, so will take his suggested path.

**Comment by tdenewiler** [comment]
I create tags/releases using the GitHub interface so that the formatting looks nicer in the [Release history](https://github.com/sscpac/statick/releases). When a tag/release is created either through GitHub interface or from pushing a locally created tag there is an automated workflow that pushes packages to Test PyPI and PyPI repositories.

If it is straightforward, I would prefer we go on the path of making the Docker build depend workflow depend on the PyPI publish workflow so that the latest tag/release ends up in the Docker build. Having it automated will reduce the likelihood of future mistakes. I'm happy to help develop/test.

**Comment by gregtkogut** [comment]
This was fixed by #448
