### ISSUE TITLE
Statick self test on Travis returns no results

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#65]
Appears to be because exceptions.yaml adds an exception for `*/build/*` and the build environment is located in /home/travis/build/sscpac/statick, so every issue trips the `*/build/*` exclude and is ignored.

**Comment by tdenewiler** [comment]
I have a potential fix for this, but there are a couple of issues that cropped up.

1. If we want to be able to run the self test on Travis and have it fail the Travis build we will need to have the exit code be non-zero if any issues are discovered. Currently, if issues are found that does not necessarily set a non-zero exit code. I am okay with making that change, but wanted to see if you are too.

2. On Travis, due to installing via pip, we are getting `pylint>=1.8.2  (from pylint-django<2.0->-r requirements.txt (line 7))`. This is a different version of pylint than what is available from xenial apt repositories (1.5.2-1ubuntu1). When running the self check against this newer version of pylint there are additional warnings generated.

If we set a non-zero exit code when issues are identified, and we are okay using the newer version of pylint, then the fixes I have for getting the self test to work on Travis means we will have to fix the new issues in Statick. None of the new issues look difficult to fix, and I am happy to do it. I just want to make sure that you don't see any problems with that approach before I do the work.

**Comment by tdenewiler** [comment]
Addressing this with #85 and #87.

**Comment by tdenewiler** [comment]
Fixed by #87.
